services:
  - type: web
    name: saree-ai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AIzaSyCAxcaDZbibBqNtqyU7eXR_x92pGon2a5w
        sync: false